var slug_lookup = {
    "australian broadcasting corporation" : "abc-news-au",
    "abc" : "abc-news-au",
    "aljazeera" : "al-jazeera-english",
    "al jazeera" : "al-jazeera-english",
    "al jazeera english" : "al-jazeera-english",
    "ars technica" : "ars-technica",
    "ap" : "associated-press",
    "associated press" : "associated-press",
    "bbc news" : "bbc-news",
    "bbc sports" : "bbc-sport",
    "bbc sport" : "bbc-sport",
    "bild" : "bild",
    "bloomberg" : "bloomberg",
    "breitbart" : "breitbart-news",
    "bussiness insider" : "business-insider",
    "business insider uk" : "business-insider-uk",
    "business insider (uk)" : "business-insider-uk",
    "buzzfeed" : "buzzfeed",
    "cnbc" : "cnbc",
    "cnn" : "cnn",
    "daily mail" : "daily-mail",
    "der tagesspiegel" : "der-tagesspiegel",
    "die zeit" : "die-zeit",
    "engadget" : "engadget",
    "entertainment weekly" : "entertainment-weekly",
    "espn" : "espn",
    "espn cric info" : "espn-cric-info",
    "espn cricinfo" : "espn-cric-info",
    "financial times" : "financial-times",
    "focus" : "focus",
    "football italia" : "football-italia",
    "fortune" : "fortune",
    "fourfourtwo" : "four-four-two",
    "four four two" : "four-four-two",
    "442" : "four-four-two",
    "fox sports" : "fox-sports",
    "google" : "google-news",
    "gruenderszene" : "gruenderszene",
    "hacker news" : "hacker-news",
    "handelsblatt" : "handelsblatt",
    "ign entertainment" : "ign",
    "ign" : "ign",
    "independent" : "independent",
    "mashable" : "mashable",
    "metro" : "metro",
    "mirror" : "mirror",
    "daily mirror" : "mirror",
    "mtv" : "mtv-news",
    "mtv news" : "mtv-news",
    "mtv news uk" : "mtv-news-uk",
    "mtv news (uk)" : "mtv-news-uk",
    "nat geo" : "national-geographic",
    "national geographic" : "national-geographic",
    "new scientist" : "new-scientist",
    "newscientist" : "new-scientist",
    "news week" : "newsweek",
    "newsweek" : "newsweek",
    "new york magazine" : "new-york-magazine",
    "newyork magazine" : "new-york-magazine",
    "nfl" : "nfl-news",
    "polygon" : "polygon",
    "recode" : "recode",
    "reddit" : "reddit-r-all",
    "reddit /r/all" : "reddit-r-all",
    "reuters" : "reuters",
    "sky news" : "sky-news",
    "sky sports news" : "sky-sports-news",
    "spiegel online" : "spiegel-online",
    "t3n" : "t3n",
    "talk sport" : "talksport",
    "talksport" : "talksport",
    "tech crunch" : "techcrunch",
    "techcrunch" : "techcrunch",
    "tech radar" : "techradar",
    "techradar" : "techradar",
    "the economist" : "the-economist",
    "economist" : "the-economist",
    "the guardian au" : "the-guardian-au",
    "the guardian uk" : "the-guardian-uk",
    "the guardian" : "the-guardian-au",
    "guardian" : "the-guardian-uk",
    "guardian au" : "the-guardian-au",
    "guardian uk" : "the-guardian-uk",
    "the hindu" : "the-hindu",
    "huffington post" : "the-huffington-post",
    "the huffington post" : "the-huffington-post",
    "lad bible" : "the-lad-bible",
    "the lad bible" : "the-lad-bible",
    "new york times" : "the-new-york-times",
    "newyork times" : "the-new-york-times",
    "the new york times" : "the-new-york-times",
    "the newyork times" : "the-new-york-times",
    "the next web" : "the-next-web",
    "the nextweb" : "the-next-web",
    "next web" : "the-next-web",
    "nextweb" : "the-next-web",
    "sport bible" : "the-sport-bible",
    "the sport bible" : "the-sport-bible",
    "the telegraph" : "the-telegraph",
    "the times of india" : "the-times-of-india",
    "times of india" : "the-times-of-india",
    "the verge" : "the-verge",
    "verge" : "the-verge",
    "wall street journal" : "the-wall-street-journal",
    "the wall street journal" : "the-wall-street-journal",
    "the washington post" : "the-washington-post",
    "washington post" : "the-washington-post",
    "time" : "time",
    "usa today" : "usa-today",
    "wired de" : "wired-de",
    "wired.de" : "wired-de",
    "wirtschafts woche" : "wirtschafts-woche"
};

module.exports.slug_lookup = slug_lookup;